[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "On"
shape = "Underline"

[debug]
log_level = "Off"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "JetBrainsMonoNL NF"
style = "Regular"

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
opacity = 0.8

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 2
y = 2

[window.position]
x = 600
y = 300
